package clientcaro;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

public class LoginCaro extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	DataInputStream inFromServer;
	DataOutputStream outToServer;

	public LoginCaro(DataInputStream inFromServer, DataOutputStream outToServer) {
		setVisible(true);
		setLocation(400, 200);
		initComponents();
		this.inFromServer = inFromServer;
		this.outToServer = outToServer;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() throws IllegalStateException {

		jLabel1 = new JLabel();
		jLabel2 = new JLabel();
		jLabel3 = new JLabel();
		t_password = new JPasswordField();
		t_username = new JTextField();
		jButton1 = new JButton();
		jButton2 = new JButton();
		jButton3 = new JButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new Font("Tahoma", 1, 18)); // NOI18N
		jLabel1.setText("Đăng nhập");

		jLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("Username:");
		jLabel2.setToolTipText("");
		jLabel2.setName("l_username"); // NOI18N

		jLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
		jLabel3.setText("Password:");
		jLabel3.setName("l_password"); // NOI18N

		t_password.setName("t_password"); // NOI18N

		t_username.setName("t_username"); // NOI18N

		jButton1.setFont(new Font("Tahoma", 3, 11)); // NOI18N
		jButton1.setText("Đăng nhập");
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new Font("Tahoma", 3, 11)); // NOI18N
		jButton2.setText("Đăng ký");
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new Font("Tahoma", 3, 11)); // NOI18N
		jButton3.setText("Thoát");
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(55, 55, 55)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel2).addComponent(jLabel3))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 148,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 148,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(31, 31, 31)
								.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29).addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(48, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(185, 185, 185).addComponent(jLabel1).addGap(0, 0,
						Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(22, 22, 22).addComponent(jLabel1).addGap(26, 26, 26)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(t_username, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
				.addGap(18, 18, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(33, 33, 33).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))
				.addGap(98, 98, 98)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		char[] temp_pwd = t_password.getPassword();
		String pwd = null;
		pwd = String.copyValueOf(temp_pwd);
		// gui username va password len server
		String loginsend = "1-" + t_username.getText() + "-" + pwd;
		try {
			// gui len server
			outToServer.writeBytes(loginsend + "\n");
			// Đọc dữ liệu Server gửi về
			String loginreceive = inFromServer.readLine();

			if (loginreceive.equals("1")) {
				Loginsuccess loginsuccess = new Loginsuccess(inFromServer, outToServer, t_username.getText());
				setVisible(false);
			} else {
				if (loginreceive.equals("0")) {
					Loginfail loginfail = new Loginfail(inFromServer, outToServer);
//                               setVisible(false);
				}
			}
			// System.exit(1);
		} catch (IOException ex) {
			Logger.getLogger(LoginCaro.class.getName()).log(Level.SEVERE, null, ex);
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		Register register = new Register(inFromServer, outToServer);
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		System.exit(0);
	}// GEN-LAST:event_jButton3ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPasswordField t_password;
	private javax.swing.JTextField t_username;
	// End of variables declaration//GEN-END:variables
}
